# PDAFMODEL variables
# -----------------------

# PDAF-Model: Set subdirectories of source code
# The source code inside `parflow` is always used, even for CLM-standalone builds
set(TSMPPDAFPFLDIR "parflow")
if(DEFINED CLM35_SRC)
  set(TSMPPDAFCLMDIR "clm3_5")
endif()
if(DEFINED eCLM_SRC)
  set(TSMPPDAFCLMDIR "eclm")
endif()

# PDAF-Model: Directory for copying static library `libmodel.a`
set(TSMPPDAFLIBDIR "${CMAKE_INSTALL_PREFIX}/lib")

# Include directories
# -------------------
# General include dirs
list(APPEND PDAF_INCLUDES "-I${NetCDF_ROOT}/include")

# DA include dirs
list(APPEND PDAF_INCLUDES "-I${PDAF_SRC}/interface/model")
list(APPEND PDAF_INCLUDES "-I${PDAF_SRC}/interface/model/common")
list(APPEND PDAF_INCLUDES "-I${PDAF_SRC}/interface/model/parflow")

# OASIS include dirs
if(DEFINED OASIS_SRC)
  list(APPEND PDAF_INCLUDES "-I${CMAKE_INSTALL_PREFIX}/OASIS3-MCT/lib/psmile.MPI1")
  list(APPEND PDAF_INCLUDES "-I${CMAKE_INSTALL_PREFIX}/OASIS3-MCT/lib/scrip")
  list(APPEND PDAF_INCLUDES "-I${CMAKE_INSTALL_PREFIX}/OASIS3-MCT/include")
endif()

# CLM include dirs
if(DEFINED CLM35_SRC)
  list(APPEND PDAF_INCLUDES "-I${CMAKE_INSTALL_PREFIX}/include/clm3.5")
endif()
if(DEFINED eCLM_SRC)
  list(APPEND PDAF_INCLUDES "-I${CMAKE_INSTALL_PREFIX}/include/eCLM")
  list(APPEND PDAF_INCLUDES "-I${CMAKE_INSTALL_PREFIX}/include/eCLM/externals/mct/include")
  list(APPEND PDAF_INCLUDES "-I${CMAKE_INSTALL_PREFIX}/include/eCLM/externals/gptl/include")
endif()

# ParFlow include dirs
if(DEFINED PARFLOW_SRC)
  list(APPEND PDAF_INCLUDES "-I${CMAKE_INSTALL_PREFIX}/include/parflow")
  # GPU:
  # list(APPEND PDAF_INCLUDES "-I${PARFLOW_SRC}/rmm/include/rmm")
endif()

# Join list of include dirs
list(JOIN PDAF_INCLUDES " " PDAF_INCLUDES)


# Libraries
# ---------

# CLM libraries
if(DEFINED CLM35_SRC)
  list(APPEND PDAF_LIBS "-L${CMAKE_INSTALL_PREFIX}/lib")
  list(APPEND PDAF_LIBS "-lclm")
endif()
if(DEFINED eCLM_SRC)
  list(APPEND PDAF_LIBS "-L${CMAKE_INSTALL_PREFIX}/lib")
  list(APPEND PDAF_LIBS "-leclm")
  list(APPEND PDAF_LIBS "-lclm")
  list(APPEND PDAF_LIBS "-ldatm")
  list(APPEND PDAF_LIBS "-lglc")
  list(APPEND PDAF_LIBS "-lgptl")
  list(APPEND PDAF_LIBS "-lice")
  list(APPEND PDAF_LIBS "-lmosart")
  list(APPEND PDAF_LIBS "-locn")
  list(APPEND PDAF_LIBS "-lpio")
  list(APPEND PDAF_LIBS "-lwav")
  list(APPEND PDAF_LIBS "-lesp")

  # The following libraries were used in CLM5-PDAF, but are not generated by eCLM
  # list(APPEND PDAF_LIBS "-latm")
  # list(APPEND PDAF_LIBS "-lrof")

  # Renamed `libmct.a`->`libmct2.a` during eCLM-build, because
  # OASIS3-MCT generates a `libmct.a` as well
  list(APPEND PDAF_LIBS "-lmct2")
  list(APPEND PDAF_LIBS "-lmpeu")

  # Important for linking that it is at the end
  list(APPEND PDAF_LIBS "-lcsm_share")
endif()

# OASIS libraries
# OASIS libraries Should be set after eCLM libraries, otherwise an
# error occurred during linking
if(DEFINED OASIS_SRC)
  list(APPEND PDAF_LIBS "${OASIS_LIBRARIES}")
endif()

# ParFlow libraries
if(DEFINED PARFLOW_SRC)
  list(APPEND PDAF_LIBS "-L${CMAKE_INSTALL_PREFIX}/lib -lpfsimulator -lamps -lpfkinsol -lgfortran -lcjson")
  # GPU
  # list(APPEND PDAF_LIBS "-L${CMAKE_INSTALL_PREFIX}/rmm/lib -lstdc++ -lcudart -lrmm -lnvToolsExt")
  list(APPEND PDAF_LIBS "-L${HYPRE_ROOT}/lib -lHYPRE")
  list(APPEND PDAF_LIBS "-L/lib64 -lslurm")
endif()

# Join list of libraries
list(JOIN PDAF_LIBS " " PDAF_LIBS)


# Precompiler definitions
# -----------------------

# General cpps
list(APPEND PDAF_DEFS "-Duse_libMPI")
list(APPEND PDAF_DEFS "-Duse_netCDF")
list(APPEND PDAF_DEFS "-Duse_comm_MPI1")
list(APPEND PDAF_DEFS "-DVERBOSE")
list(APPEND PDAF_DEFS "-DDEBUG")
list(APPEND PDAF_DEFS "-DTREAT_OVERLAY")
list(APPEND PDAF_DEFS "-DFORTRANUNDERSCORE")
list(APPEND PDAF_DEFS "-DOFFLINE")
list(APPEND PDAF_DEFS "-DSPMD")
list(APPEND PDAF_DEFS "-DLINUX")

if(DEFINED OASIS_SRC)
  list(APPEND PDAF_DEFS "-Duse_comm_da")
  list(APPEND PDAF_DEFS "-DMAXPATCH_PFT=1")
  if(DEFINED PARFLOW_SRC)
    list(APPEND PDAF_DEFS "-DCOUP_OAS_PFL")
    list(APPEND PDAF_DEFS "-DOBS_ONLY_PARFLOW")
  endif()
  if(DEFINED eCLM_SRC)
    list(APPEND PDAF_DEFS "-DCLMFIVE")
  endif()
else()
  if(DEFINED CLM35_SRC)
    list(APPEND PDAF_DEFS "-DCLMSA")
  endif()
  if(DEFINED eCLM_SRC)
    list(APPEND PDAF_DEFS "-DCLMSA")
    list(APPEND PDAF_DEFS "-DCLMFIVE")
  endif()
endif()

if (CMAKE_BUILD_TYPE STREQUAL "DEBUG")
  # Debug run: Define `PDAF_DEBUG`
  list(APPEND PDAF_DEFS "-DPDAF_DEBUG")
endif()

# Join list of precompiler definitions
list(JOIN PDAF_DEFS " " PDAF_DEFS)


# Set env vars required by PDAF Makefiles
# ---------------------------------------
# Additionally system environment variables are used by the Makefiles
# f.e. `EBROOTHYPRE`, etc, or `MKLROOT`
list(APPEND PDAFMODEL_ENV_VARS PDAF_ARCH=${PDAF_ARCH})
list(APPEND PDAFMODEL_ENV_VARS PDAF_DIR=${PDAF_DIR})
list(APPEND PDAFMODEL_ENV_VARS TSMPPDAFLINK_LIBS=${PDAF_LINK_LIBS})
list(APPEND PDAFMODEL_ENV_VARS TSMPPDAFOPTIM=${PDAF_OPTIM})
list(APPEND PDAFMODEL_ENV_VARS TSMPPDAFMPI_INC=${PDAF_MPI_INC})
list(APPEND PDAFMODEL_ENV_VARS TSMPPDAFCPP_DEFS=${PDAF_CPP_DEFS})
list(APPEND PDAFMODEL_ENV_VARS TSMPPDAFIMPORTFLAGS=${PDAF_INCLUDES})
list(APPEND PDAFMODEL_ENV_VARS TSMPPDAFCPPDEFS=${PDAF_DEFS})
list(APPEND PDAFMODEL_ENV_VARS TSMPPDAFLIBS=${PDAF_LIBS})
list(APPEND PDAFMODEL_ENV_VARS TSMPPDAFLIBDIR=${TSMPPDAFLIBDIR})
list(APPEND PDAFMODEL_ENV_VARS TSMPPDAFPFLDIR=${TSMPPDAFPFLDIR})
list(APPEND PDAFMODEL_ENV_VARS TSMPPDAFCLMDIR=${TSMPPDAFCLMDIR})

# PDAF-Model: Append variables for checking existing component models
if(DEFINED eCLM_SRC)
  list(APPEND PDAFMODEL_ENV_VARS eCLM_SRC="${eCLM_SRC}")
endif()
if(DEFINED CLM35_SRC)
  list(APPEND PDAFMODEL_ENV_VARS CLM35_SRC="${CLM35_SRC}")
endif()
if(DEFINED ICON_SRC)
  list(APPEND PDAFMODEL_ENV_VARS ICON_SRC="${ICON_SRC}")
endif()
if(DEFINED COSMO_SRC)
  list(APPEND PDAFMODEL_ENV_VARS COSMO_SRC="${COSMO_SRC}")
endif()
if(DEFINED PARFLOW_SRC)
  list(APPEND PDAFMODEL_ENV_VARS PARFLOW_SRC="${PARFLOW_SRC}")
endif()

ExternalProject_Add(PDAF-Model
  PREFIX            PDAF-Model
  SOURCE_DIR        ${PDAF_SRC}/interface/model
  BUILD_IN_SOURCE   TRUE
  CONFIGURE_COMMAND ""
  BUILD_COMMAND     make ${PDAFMODEL_ENV_VARS} clean all
  INSTALL_COMMAND   ""
  DEPENDS           PDAF
)
