# PDAFFRAMEWORK variables
# -----------------------

# PDAF-Framework: Directory for copying executable `tsmp-pdaf`
set(TSMPPDAFBINDIR "${CMAKE_INSTALL_PREFIX}/bin")

# Set env vars required by PDAF Makefiles
# ---------------------------------------
# Additionally system environment variables are used by the Makefiles
# f.e. `EBROOTHYPRE`, etc, or `MKLROOT`
list(APPEND PDAFFRAMEWORK_ENV_VARS TSMPPDAFIMPORTFLAGS=${PDAF_INCLUDES})
list(APPEND PDAFFRAMEWORK_ENV_VARS TSMPPDAFCPPDEFS=${PDAF_DEFS})
list(APPEND PDAFFRAMEWORK_ENV_VARS TSMPPDAFLIBS=${PDAF_LIBS})
list(APPEND PDAFFRAMEWORK_ENV_VARS PDAF_ARCH=${PDAF_ARCH})
list(APPEND PDAFFRAMEWORK_ENV_VARS PDAF_DIR=${PDAF_DIR})
list(APPEND PDAFFRAMEWORK_ENV_VARS TSMPPDAFLIBDIR=${TSMPPDAFLIBDIR})
list(APPEND PDAFFRAMEWORK_ENV_VARS TSMPPDAFBINDIR=${TSMPPDAFBINDIR})
list(APPEND PDAFFRAMEWORK_ENV_VARS TSMPPDAFPFLDIR=${TSMPPDAFPFLDIR})
list(APPEND PDAFFRAMEWORK_ENV_VARS TSMPPDAFCLMDIR=${TSMPPDAFCLMDIR})

# make pdaf framework
ExternalProject_Add(PDAF-Framework
  PREFIX            PDAF-Framework
  SOURCE_DIR        ${PDAF_SRC}/interface/framework
  BUILD_IN_SOURCE   TRUE
  CONFIGURE_COMMAND ""
  BUILD_COMMAND     make ${PDAFFRAMEWORK_ENV_VARS} clean all
  INSTALL_COMMAND   ""
  DEPENDS           ${PDAF_DEPENDENCIES} PDAF PDAF-Model
)
