name: TSMP2 Build

# Controls when the action will run.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  eclm_build_job:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04 ]
        config:
        - {
            name: "CLM3.5-PDAF",
            use_oasis: "False"
          }
        - {
            name: "eCLM-PDAF",
            use_oasis: "False"
          }
        - {
            name: "ICON-eCLM-ParFlow",
            use_oasis: "True",
            parflow_dir: "parflow"
          }
        - {
            name: "CLM3.5-ParFlow-PDAF",
            use_oasis: "True",
            parflow_dir: "parflow_pdaf"
          }
        - {
            name: "eCLM-ParFlow-PDAF",
            use_oasis: "True",
            parflow_dir: "parflow_pdaf"
          }
    env:
      SYSTEMNAME: UBUNTU
      STAGE: 24.04
      CC: mpicc
      CXX: mpic++
      FC: mpifort
      F77: mpif77
      MPI_HOME: /usr/lib/x86_64-linux-gnu/openmpi
      VER_NETCDF_C: 4.9.2
      VER_NETCDF_F90: 4.6.1
      VER_HYPRE: 2.26.0
      VER_ECCODES: 2.40.0

    steps:
      - uses: actions/checkout@v4

      # These apt packages have post-install step which can't be triggered by GitHub cache.
      - name: Install TSMP2 dependencies on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install gfortran openmpi-bin libopenmpi-dev libhdf5-openmpi-dev libhdf5-openmpi-hl-fortran-100t64 hdf5-helpers liblapack-dev libblas-dev

      # These apt packages can be safely cached.
      - name: Install extra TSMP2 dependencies on Ubuntu
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxml++2.6-dev pylint wget cmake libpnetcdf-dev tcl-dev tk-dev liblzma-dev
          version: 1.0
          execute_install_scripts: true

      - name: Initialized dependency directory and variables
        run: |
          TSMP2_ROOT=$(git rev-parse --show-toplevel)
          DEPENDENCIES_ROOT=${TSMP2_ROOT}/dependencies
          mkdir -v ${DEPENDENCIES_ROOT}
          tree -L 1 ${TSMP2_ROOT}
          echo "TSMP2_ROOT=${TSMP2_ROOT}" >> $GITHUB_ENV
          echo "DEPENDENCIES_ROOT=${DEPENDENCIES_ROOT}" >> $GITHUB_ENV

      #
      # NetCDF C
      #
      - name: Restore cached netcdf-c-${{ env.VER_NETCDF_C }}
        uses: actions/cache/restore@v4
        id: cache-netcdf-c-restore
        with:
          path: ${{ env.DEPENDENCIES_ROOT }}/netcdf-c-${{ env.VER_NETCDF_C }}
          key: ${{ matrix.config.name }}_netcdf-c-${{ env.VER_NETCDF_C }}

      - if: steps.cache-netcdf-c-restore.outputs.cache-hit != 'true'
        name: Install netcdf-c-${{ env.VER_NETCDF_C }}
        working-directory: /tmp
        run: |
          # Download
          wget https://github.com/Unidata/netcdf-c/archive/v${VER_NETCDF_C}.tar.gz
          tar xf v${VER_NETCDF_C}.tar.gz
          cd netcdf-c-${VER_NETCDF_C}

          # Install
          export CPPFLAGS=-I/usr/include/hdf5/openmpi
          export LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/openmpi
          ./configure --prefix=${DEPENDENCIES_ROOT}/netcdf-c-${VER_NETCDF_C}
          make -j4 install

          # Verify
          tree -L 2 ${DEPENDENCIES_ROOT}/netcdf-c-${VER_NETCDF_C}

          # For TSMP2 dependency discovery
          echo "CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:${DEPENDENCIES_ROOT}/netcdf-c-${VER_NETCDF_C}" >> $GITHUB_ENV

      - if: steps.cache-netcdf-c-restore.outputs.cache-hit != 'true'
        name: Cache netcdf-c-${{ env.VER_NETCDF_C }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.DEPENDENCIES_ROOT }}/netcdf-c-${{ env.VER_NETCDF_C }}
          key: ${{ matrix.config.name }}_netcdf-c-${{ env.VER_NETCDF_C }}

      #
      # NetCDF Fortran
      #
      - name: Restore cached netcdf-f90-${{ env.VER_NETCDF_F90 }}
        uses: actions/cache/restore@v4
        id: cache-netcdf-f90-restore
        with:
          path: ${{ env.DEPENDENCIES_ROOT }}/netcdf-f90-${{ env.VER_NETCDF_F90 }}
          key: ${{ matrix.config.name }}_netcdf-f90-${{ env.VER_NETCDF_F90 }}

      - if: steps.cache-netcdf-f90-restore.outputs.cache-hit != 'true'
        name: Install netcdf-f90-${{ env.VER_NETCDF_F90 }}
        working-directory: /tmp
        run: |
          # Download
          wget https://github.com/Unidata/netcdf-fortran/archive/v${VER_NETCDF_F90}.tar.gz
          tar xf v${VER_NETCDF_F90}.tar.gz
          cd netcdf-fortran-${VER_NETCDF_F90}

          # Install
          export CPPFLAGS=-I${DEPENDENCIES_ROOT}/netcdf-c-${VER_NETCDF_C}/include
          export LDFLAGS=-L${DEPENDENCIES_ROOT}/netcdf-c-${VER_NETCDF_C}/lib
          ./configure --prefix=${DEPENDENCIES_ROOT}/netcdf-f90-${VER_NETCDF_F90}
          make -j4 install

          # Verify
          tree -L 2 ${DEPENDENCIES_ROOT}/netcdf-f90-${VER_NETCDF_F90}

          # For TSMP2 dependency discovery
          echo "CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:${DEPENDENCIES_ROOT}/netcdf-f90-${VER_NETCDF_F90}" >> $GITHUB_ENV

      - if: steps.cache-netcdf-f90-restore.outputs.cache-hit != 'true'
        name: Cache netcdf-f90-${{ env.VER_NETCDF_F90 }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.DEPENDENCIES_ROOT }}/netcdf-f90-${{ env.VER_NETCDF_F90 }}
          key: ${{ matrix.config.name }}_netcdf-f90-${{ env.VER_NETCDF_F90 }}

      #
      # Hypre
      #
      - if: contains(matrix.config.name, 'ParFlow')
        name: Restore cached hypre-${{ env.VER_HYPRE }}
        uses: actions/cache/restore@v4
        id: cache-hypre-restore
        with:
          path: ${{ env.DEPENDENCIES_ROOT }}/hypre-${{ env.VER_HYPRE }}
          key: ${{ matrix.config.name }}_hypre-${{ env.VER_HYPRE }}

      - if: contains(matrix.config.name, 'ParFlow') && steps.cache-hypre-restore.outputs.cache-hit != 'true'
        name: Install hypre-${{ env.VER_HYPRE }}
        working-directory: /tmp
        run: |
          # Download
          wget https://github.com/hypre-space/hypre/archive/v${VER_HYPRE}.tar.gz
          tar xf v${VER_HYPRE}.tar.gz
          cd hypre-${VER_HYPRE}/src

          # Install
          ./configure --prefix=${DEPENDENCIES_ROOT}/hypre-${VER_HYPRE }
          make -j4 install

          # Verify
          tree -L 2 ${DEPENDENCIES_ROOT}/hypre-${VER_HYPRE }

          # For TSMP2 dependency discovery
          echo "CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:${DEPENDENCIES_ROOT}/hypre-${VER_HYPRE }" >> $GITHUB_ENV

      - if: contains(matrix.config.name, 'ParFlow') && steps.cache-hypre-restore.outputs.cache-hit != 'true'
        name: Cache hypre-${{ env.VER_HYPRE }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.DEPENDENCIES_ROOT }}/hypre-${{ env.VER_HYPRE }}
          key: ${{ matrix.config.name }}_hypre-${{ env.VER_HYPRE }}

      #
      # ecCodes
      #
      - if: contains(matrix.config.name, 'ICON')
        name: Restore cached eccodes-${{ env.VER_ECCODES }}
        uses: actions/cache/restore@v4
        id: cache-eccodes-restore
        with:
          path: ${{ env.DEPENDENCIES_ROOT }}/eccodes-${{ env.VER_ECCODES }}
          key: ${{ matrix.config.name }}_eccodes-${{ env.VER_ECCODES }}

      - if: contains(matrix.config.name, 'ICON') && steps.cache-eccodes-restore.outputs.cache-hit != 'true'
        name: Install eccodes-${{ env.VER_ECCODES }}
        working-directory: /tmp
        run: |
          # Download
          wget https://github.com/ecmwf/eccodes/archive/refs/tags/${VER_ECCODES}.tar.gz
          tar xf ${VER_ECCODES}.tar.gz
          cd eccodes-${VER_ECCODES}

          # Install
          cmake -S . -B bld -DCMAKE_INSTALL_PREFIX=${DEPENDENCIES_ROOT}/eccodes-${VER_ECCODES }
          cmake --build bld --parallel 4
          cmake --install bld

          # Verify
          tree -L 2 ${DEPENDENCIES_ROOT}/eccodes-${VER_ECCODES }

          # For TSMP2 dependency discovery
          echo "CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:${DEPENDENCIES_ROOT}/eccodes-${VER_ECCODES }" >> $GITHUB_ENV

      - if: contains(matrix.config.name, 'ICON') && steps.cache-eccodes-restore.outputs.cache-hit != 'true'
        name: Cache eccodes-${{ env.VER_ECCODES }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.DEPENDENCIES_ROOT }}/eccodes-${{ env.VER_ECCODES }}
          key: ${{ matrix.config.name }}_eccodes-${{ env.VER_ECCODES }}

      #
      # Check component model versions
      #
      - name: Extract required component model versions
        id: model-versions
        working-directory: ${{ env.TSMP2_ROOT }}/models
        run: |
          pwd && ls
          git submodule status | cut -c2- | tee model_versions

          if [[ "${{ matrix.config.use_oasis }}" == "True" ]]; then
            VER_OASIS=$(cat model_versions | grep " oasis3-mct" | cut -d' ' -f1)
            echo "VER_OASIS=${VER_OASIS}"
            echo "VER_OASIS=${VER_OASIS}" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ matrix.config.name }}" == *"eCLM"* ]]; then
            VER_eCLM=$(cat model_versions | grep " eCLM" | cut -d' ' -f1)
            echo "VER_eCLM=${VER_eCLM}"
            echo "VER_eCLM=${VER_eCLM}" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ matrix.config.name }}" == *"CLM3.5"* ]]; then
            VER_CLM35=$(cat model_versions | grep " CLM3.5" | cut -d' ' -f1)
            echo "VER_CLM35=${VER_CLM35}"
            echo "VER_CLM35=${VER_CLM35}" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ matrix.config.name }}" == *"ParFlow"* ]]; then
            VER_ParFlow=$(cat model_versions | grep " ${{ matrix.config.parflow_dir }}"  | cut -d' ' -f1)
            echo "VER_ParFlow=${VER_ParFlow}"
            echo "VER_ParFlow=${VER_ParFlow}" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ matrix.config.name }}" == *"ICON"* ]]; then
            VER_ICON=$(cat model_versions | grep " icon" | cut -d' ' -f1)
            echo "VER_ICON=${VER_ICON}"
            echo "VER_ICON=${VER_ICON}" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ matrix.config.name }}" == *"PDAF"* ]]; then
            VER_PDAF=$(cat model_versions | grep " pdaf" | cut -d' ' -f1)
            echo "VER_PDAF=${VER_PDAF}"
            echo "VER_PDAF=${VER_PDAF}" >> $GITHUB_OUTPUT
          fi

      #
      # OASIS3-MCT
      #
      - if: matrix.config.use_oasis == 'True'
        name: Restore cached OASIS3-MCT submodule ${{ steps.model-versions.outputs.VER_OASIS }}
        uses: actions/cache/restore@v4
        id: cache-oasis-restore
        with:
          path: ${{ env.TSMP2_ROOT }}/models/oasis3-mct
          key: ${{ matrix.config.name }}_oasis-${{ steps.model-versions.outputs.VER_OASIS }}

      - if: matrix.config.use_oasis == 'True' && steps.cache-oasis-restore.outputs.cache-hit != 'true'
        name: Update OASIS3-MCT submodule ${{ steps.model-versions.outputs.VER_OASIS }}
        working-directory: ${{ env.TSMP2_ROOT }}/models/oasis3-mct
        run: |
          pwd && git submodule update --init --force .

      - if: matrix.config.use_oasis == 'True' && steps.cache-oasis-restore.outputs.cache-hit != 'true'
        name: Cache OASIS3-MCT submodule ${{ steps.model-versions.outputs.VER_OASIS }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.TSMP2_ROOT }}/models/oasis3-mct
          key: ${{ matrix.config.name }}_oasis-${{ steps.model-versions.outputs.VER_OASIS }}

      #
      # eCLM
      #
      - if: contains(matrix.config.name, 'eCLM')
        name: Restore cached eCLM
        uses: actions/cache/restore@v4
        id: cache-eclm-restore
        with:
          path: ${{ env.TSMP2_ROOT }}/models/eCLM
          key: ${{ matrix.config.name }}_eclm-${{ steps.model-versions.outputs.VER_eCLM }}

      - if: contains(matrix.config.name, 'eCLM') && steps.cache-eclm-restore.outputs.cache-hit != 'true'
        name: Update eCLM submodule ${{ steps.model-versions.outputs.VER_eCLM }}
        working-directory: ${{ env.TSMP2_ROOT }}/models/eCLM
        run: |
          pwd && git submodule update --init --force .
          echo "TSMP2_MODEL_OPTS=${TSMP2_MODEL_OPTS} --eCLM" >> $GITHUB_ENV

      - if: contains(matrix.config.name, 'eCLM') && steps.cache-eclm-restore.outputs.cache-hit != 'true'
        name: Cache eCLM submodule ${{ steps.model-versions.outputs.VER_eCLM }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.TSMP2_ROOT }}/models/eCLM
          key: ${{ matrix.config.name }}_eclm-${{ steps.model-versions.outputs.VER_eCLM }}

      #
      # CLM3.5
      #
      - if: contains(matrix.config.name, 'CLM3.5')
        name: Restore cached CLM3.5 submodule ${{ steps.model-versions.outputs.VER_CLM35 }}
        uses: actions/cache/restore@v4
        id: cache-clm35-restore
        with:
          path: ${{ env.TSMP2_ROOT }}/models/CLM3.5
          key: ${{ matrix.config.name }}_clm3.5-${{ steps.model-versions.outputs.VER_CLM35 }}

      - if: contains(matrix.config.name, 'CLM3.5') && steps.cache-clm35-restore.outputs.cache-hit != 'true'
        name: Update CLM3.5 submodule ${{ steps.model-versions.outputs.VER_CLM35 }}
        working-directory: ${{ env.TSMP2_ROOT }}/models/CLM3.5
        run: |
          pwd && git submodule update --init --force .
          echo "TSMP2_MODEL_OPTS=${TSMP2_MODEL_OPTS} --CLM35" >> $GITHUB_ENV

      - if: contains(matrix.config.name, 'CLM3.5') && steps.cache-clm35-restore.outputs.cache-hit != 'true'
        name: Cache CLM3.5 submodule ${{ steps.model-versions.outputs.VER_CLM35 }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.TSMP2_ROOT }}/models/CLM3.5
          key: ${{ matrix.config.name }}_clm3.5-${{ steps.model-versions.outputs.VER_CLM35 }}

      #
      # ParFlow
      #
      - if: contains(matrix.config.name, 'ParFlow')
        name: Restore cached ${{ matrix.config.parflow_dir }} submodule ${{ steps.model-versions.outputs.VER_ParFlow }}
        uses: actions/cache/restore@v4
        id: cache-parflow-restore
        with:
          path: ${{ env.TSMP2_ROOT }}/models/${{ matrix.config.parflow_dir }}
          key: ${{ matrix.config.name }}_${{ matrix.config.parflow_dir }}-${{ steps.model-versions.outputs.VER_ParFlow }}

      - if: contains(matrix.config.name, 'ParFlow') && steps.cache-parflow-restore.outputs.cache-hit != 'true'
        name: Update ${{ matrix.config.parflow_dir }} submodule ${{ steps.model-versions.outputs.VER_ParFlow }}
        working-directory: ${{ env.TSMP2_ROOT }}/models/${{ matrix.config.parflow_dir }}
        run: |
          pwd && git submodule update --init --force .
          echo "TSMP2_MODEL_OPTS=${TSMP2_MODEL_OPTS} --ParFlow" >> $GITHUB_ENV

      - if: contains(matrix.config.name, 'ParFlow') && steps.cache-parflow-restore.outputs.cache-hit != 'true'
        name: Cache ${{ matrix.config.parflow_dir }} submodule ${{ steps.model-versions.outputs.VER_ParFlow }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.TSMP2_ROOT }}/models/${{ matrix.config.parflow_dir }}
          key: ${{ matrix.config.name }}_${{ matrix.config.parflow_dir }}-${{ steps.model-versions.outputs.VER_ParFlow }}

      #
      # ICON
      #
      - if: contains(matrix.config.name, 'ICON')
        name: Restore cached ICON submodule ${{ steps.model-versions.outputs.VER_ICON }}
        uses: actions/cache/restore@v4
        id: cache-icon-restore
        with:
          path: ${{ env.TSMP2_ROOT }}/models/icon
          key: ${{ matrix.config.name }}_icon-${{ steps.model-versions.outputs.VER_ICON }}

      - if: contains(matrix.config.name, 'ICON') && steps.cache-icon-restore.outputs.cache-hit != 'true'
        name: Update ICON submodule ${{ steps.model-versions.outputs.VER_ICON }}
        working-directory: ${{ env.TSMP2_ROOT }}/models/icon
        run: |
          pwd && git submodule update --init --force .
          echo "TSMP2_MODEL_OPTS=${TSMP2_MODEL_OPTS} --ICON" >> $GITHUB_ENV

      - if: contains(matrix.config.name, 'ICON') && steps.cache-icon-restore.outputs.cache-hit != 'true'
        name: Cache ICON submodule ${{ steps.model-versions.outputs.VER_ICON }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.TSMP2_ROOT }}/models/icon
          key: ${{ matrix.config.name }}_icon-${{ steps.model-versions.outputs.VER_ICON }}

      #
      # PDAF
      #
      - if: contains(matrix.config.name, 'PDAF')
        name: Restore cached PDAF submodule ${{ steps.model-versions.outputs.VER_PDAF }}
        uses: actions/cache/restore@v4
        id: cache-pdaf-restore
        with:
          path: ${{ env.TSMP2_ROOT }}/models/pdaf
          key: ${{ matrix.config.name }}_pdaf-${{ steps.model-versions.outputs.VER_PDAF }}

      - if: contains(matrix.config.name, 'PDAF') && steps.cache-pdaf-restore.outputs.cache-hit != 'true'
        name: Update PDAF submodule ${{ steps.model-versions.outputs.VER_PDAF }}
        working-directory: ${{ env.TSMP2_ROOT }}/models/pdaf
        run: |
          pwd && git submodule update --init --force .
          echo "TSMP2_MODEL_OPTS=${TSMP2_MODEL_OPTS} --PDAF" >> $GITHUB_ENV

      - if: contains(matrix.config.name, 'PDAF') && steps.cache-pdaf-restore.outputs.cache-hit != 'true'
        name: Cache PDAF submodule ${{ steps.model-versions.outputs.VER_PDAF }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.TSMP2_ROOT }}/models/pdaf
          key: ${{ matrix.config.name }}_pdaf-${{ steps.model-versions.outputs.VER_PDAF }}

      #
      # Pre-build checks
      #
      - name: Check component model versions
        working-directory: ${{ env.TSMP2_ROOT }}/models
        run: |
          pwd && ls
          git submodule foreach 'git rev-parse HEAD'
          echo ""
          git submodule status | grep -vE "^-"

      - name: Check TSMP2 dependencies and build_tsmp2 model flags
        run: |
          tree -L 2 ${DEPENDENCIES_ROOT}
          echo "CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}"
          echo "Model flags: ${TSMP2_MODEL_OPTS}"

      #
      # Build TSMP2
      #
      - name: Build ${{ matrix.config.name }}
        run: |
          echo "TSMP2_MODEL_OPTS=${TSMP2_MODEL_OPTS}"
          ./build_tsmp2.sh ${TSMP2_MODEL_OPTS} --no_update --compiler gnu
          tree -L 4 bin
